### ISSUE TITLE
астанавитесь

### ISSUE THREAD

**Issue by ssslambda** [evoytenkoapps/angular-best-practices#12]
я конечно дико извиняюсь но я не вижу описания плюшек от соблюдения правил которые содержатся в readme (пример: don't use any, почему я не должен его использовать? как я должен понять что это уместно или нет? ответа не дано), еще и оригинал на английском без перевода (стоит подумать о тех кому сложно английский читать), у нодовских бестпрактисов к примеру описано что мы получаем взамен соблюдения правилам и есть перевод

**Comment by evoytenkoapps** [comment]
Привет! Хорошо, возможно в будущем попробую написать. Конкретно any плох тем что он удаляет бизнес логику в приложении. С ним приложение становится просто набором букв, который невозможно поддерживать и дебажить, т.к. ты не знаешь какая именно сущность используется в данный момент.
