### ISSUE TITLE
Зависимости

### ISSUE THREAD

**Issue by WuglyakBolgoink** [evoytenkoapps/angular-best-practices#4]
> Зависимости
> Устанавливаем зависимости по согласованию
> 
> Зависимости должны устанавливаться с возможностью обновления только patch версии. Для этого указываем символ ~ и номер версии в package.json.

это вообще плохой тон и приводит к несостыковке версий между машинами... В "лучших практиках" применимо понятие "фиксированная версия" без всяких тильд и домиков и прочих динамических версий! чтобы при `npm install` всегда устанавливалась только та версия пакета и их завасимостей, которая прописана в package.json, а не та, которая может случайно прилететь патчем и никто и не поймет что произошло на самом деле если что-либо отвалится!

**Comment by evoytenkoapps** [comment]
Спорный момент. Несколько опытных программистов рекомендовали использовать '~' чтобы баги правились. Если еще кто напишет что это неправильно и почеу, я поправлю.

**Comment by SonyStone** [comment]
Да, лучше ставить фиксированную версию.
На проектах было множества проблем когда у npm пакетов ломалась обратная совместимость на patch версии.
Большинство пакетов очень плохо соблюдают npm versioning semantic.

**Comment by evoytenkoapps** [comment]
лады, поменяю https://stackoverflow.com/a/25861938/7160632
