### ISSUE TITLE
RXJS

### ISSUE THREAD

**Issue by savylovskij** [evoytenkoapps/angular-best-practices#9]
Мне кажеться более правильный вариант будет использовать ReplaySubject для отписок.
Предлагаю
const destroy$: Subject<void> = new Subject();
Заменить на 
const destroy$ = new ReplaySubject(1);
https://medium.com/ngx/why-do-you-need-unsubscribe-ee0c62b5d21f

Или использовать вариант сервиса например как тут https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/cdk/services/destroy.service.ts#L8.

**Comment by evoytenkoapps** [comment]
Да, спасибо. Изменил на ReplaySubject . А сервис отписки у меня уже где-то есть в примерах, я его скопировал у Alex Inkin
